#ifndef CRONUS_DISPLAY_H
#define CRONUS_DISPLAY_H

#include "cronus/cfg.h"

#ifdef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_32X16_ENABLED
#ifndef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_32X16_RX
#define CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_32X16_RX 0
#endif
#ifndef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_32X16_RY
#define CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_32X16_RY 0
#endif
#endif // CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_ENABLED

dy_err_t init_display(cronus_cfg_display_type_t dt);

#endif // CRONUS_DISPLAY_H