#ifndef CRONUS_DISPLAY_H
#define CRONUS_DISPLAY_H

typedef enum {
    CRONUS_DISPLAY_TYPE_NONE,
    CRONUS_DISPLAY_TYPE_MAX7219_32X8,
    CRONUS_DISPLAY_TYPE_MAX7219_32X16,
} cronus_display_type_t;

#ifdef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_ENABLED
#ifndef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RX
#define CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RX 0
#endif
#ifndef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RY
#define CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RY 0
#endif
#endif // CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_ENABLED

dy_err_t init_display(cronus_display_type_t dt);

#endif // CRONUS_DISPLAY_H