#ifndef CRONUS_DISPLAY_H
#define CRONUS_DISPLAY_H

#ifdef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_ENABLED
#ifndef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RX
#define CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RX 0
#endif
#ifndef CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RY
#define CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_RY 0
#endif
#endif // CONFIG_CRONUS_DISPLAY_DRIVER_MAX7219_ENABLED

dy_err_t init_display();

#endif // CRONUS_DISPLAY_H