on:
  - push
  - workflow_dispatch
jobs:
  esp32s3_max7219v32x16:
    uses: ashep/ci/.github/workflows/esp-idf-build.yaml@v1
    with:
      workdir: src
      app_name: cronus
      app_target: esp32s3_max7219v32x16
  esp32s3_ws2812v32x16:
    uses: ashep/ci/.github/workflows/esp-idf-build.yaml@v1
    with:
      workdir: src
      app_name: cronus
      app_target: esp32s3_ws2812v32x16
  publish-release:
    uses: ashep/ci/.github/workflows/publish-release.yaml@v1
    if: ${{ github.ref_type == 'tag' }}
    needs:
      - esp32s3_max7219v32x16
      - esp32s3_ws2812v32x16
    permissions:
        contents: write # mandatory for creating releases
    with:
      app_name: cronus
