on: push
jobs:
  firmware-esp32s3_max7219v32x16:
    name: Firmware (ESP32S3, MAX7219, 32x16)
    uses: ashep/ci/.github/workflows/esp-idf-build.yaml@v1
    permissions:
      contents: write # for creating releases
    with:
      app_name: cronus
      app_target: esp32s3_max7219v32x16
      workdir: firmware

  build-frontend:
    uses: ashep/ci/.github/workflows/js-build.yaml@v1
    with:
      workdir: frontend
      app_name: ${{ github.event.repository.name }}-gui
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-frontend:
    uses: ashep/ci/.github/workflows/deploy-docker.yaml@v1
    needs:
      - build-frontend
    with:
      workdir: frontend
      app_name: ${{ github.event.repository.name }}-gui
      ssh_host: ${{ vars.DEPLOY_SSH_HOST }}
      ssh_port: ${{ vars.DEPLOY_SSH_PORT }}
      ssh_user: ${{ vars.DEPLOY_SSH_USER }}
      dotenv: |
        HTTP_PORT=${{ vars.FRONTEND_SVC_LOCAL_HTTP_PORT }}

    secrets:
      ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
